
name: 'deploy-cops-action'
description: 'Action to deploy application on COPS'
inputs:
  url:
    description: 'Application url in COPS'
    required: true
  image:
    description: 'Full image path with version'
    required: true
runs:
  using: 'composite'
  steps:
    - run: python --version

    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        URL: ${{ inputs.url }}
        IMAGE: ${{ inputs.image }}
