
name: 'deploy-cops-action'
description: 'Action to deploy application on COPS'
inputs:
  url:
    description: 'Application url in COPS'
    required: true
  image:
    description: 'Full image path with version'
    required: true
  timeout_in_seconds:
    description: 'Max timeout to wait deploy to finish'
    default: 600
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        TIMEOUT: ${{ inputs.timeout_in_seconds }}
        URL: ${{ inputs.url }}
